#!/usr/bin/env python

import sys
import time
import logging
import os
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

daemons = []
TMP_DIR = "/tmp/voror"
CONFIG_FILE = "/etc/voror/voror.conf"

class RestartEventHandler(FileSystemEventHandler):
    def handle_restart(self, event):
        os.system("/etc/init.d/%s restart" %(os.path.basename(event.src_path)))
    def on_created(self, event):
        self.handle_restart(event)
    def on_modified(self, event):
        self.handle_restart(event)

if __name__ == "__main__":
    with open(CONFIG_FILE) as f:
        daemons = [line for line in f]

    if not os.path.exists(TMP_DIR):
        os.mkdir(TMP_DIR)

    observer = Observer()
    event_handler = RestartEventHandler()
    observer.schedule(event_handler, TMP_DIR, recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
