#!/usr/bin/env python

import sys
import time
import logging
import os
import signal
import multiprocessing
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

TMP_DIR = "/tmp/voror"
CONFIG_FILE = "/etc/voror/voror.conf"

daemons = []

stop_event = multiprocessing.Event()

def stop(signum, frame):
    stop_event.set()

signal.signal(signal.SIGTERM, stop)

class RestartEventHandler(FileSystemEventHandler):
    def handle_restart(self, event):
        os.system("/etc/init.d/%s restart" %(os.path.basename(event.src_path)))
    def on_created(self, event):
        self.handle_restart(event)
    def on_modified(self, event):
        self.handle_restart(event)

if __name__ == "__main__":
    with open(CONFIG_FILE) as f:
        daemons = [line for line in f]

    if not os.path.exists(TMP_DIR):
        os.mkdir(TMP_DIR)

    observer = Observer()
    event_handler = RestartEventHandler()
    observer.schedule(event_handler, TMP_DIR, recursive=True)
    observer.start()

    while not stop_event.is_set():
        time.sleep(3)

    observer.join()
