#!/bin/sh

# Add to defaults by running:
#  sudo update-rc.d voror defaults

set -e

# Must be a valid filename
NAME=voror
#/var/run must be writable by your user
PIDFILE=/var/run/voror.pid
DAEMON="/etc/voror/voror"

APPDIR=/etc/voror

start() {
  start-stop-daemon --background --start --quiet --chuid $USER --pidfile $PIDFILE \
    --exec $DAEMON
}

stop() {
  start-stop-daemon --stop --quiet --pidfile $PID \
    --retry 5
}

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        stop
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        stop
        start
        echo "."
        ;;

  *)
        echo "Usage: "$1" {start|stop|restart}"
        exit 1
esac

exit 0
